version: '3'

services:
  app:
    container_name: travelHackServer
    build: .
    ports:
      - '3080:3080'
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db
volumes:
  data-volume:
